pipeline{
    agent any

    stages{
        stage('Access MongoDB Connection String')
        {
            steps{
                script{
                   withCredentials([string(credentialsId:'mongo-uri',variable:"MONGO_URI")])
                   {
                    sh "echo MongoDB Connection String: $MONGO_URI"
                   }
                }
            }
        }
    }


}