pipeline
{
    agent any
    stages{
        stage("Build")
        {
            steps{
                script{
                    sh exit 0
                }
            }
        }

        stage("Test")
        {
            steps{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE')
                {
                    echo "Running Test Stage"
                    sh exit 1
                }
            }
        }
        stage("Deploy")
        {
            steps{
                echo "Running Deploy Stage"
                sh 'echo deploying application...'
            }
        }

    }
}