pipeline{
  agent any
  tools {
    nodejs  "nodejs-18.17.1"
  }
  stages{
    stage("Checkout Code")
    {
        steps{
            dir("express-repo")
            {
                git url: 'https://github.com/expressjs/express.git', branch: 'master'
            }
        }
    }
    stage('Print NodeJS and NPM Versions')
    {
        steps{
            sh 'node -v'
            sh 'npm -v'
        }
    }
    stage("Install Dependencies")
    {
        steps{
            dir("express-repo")
            {
                sh 'npm install'
            }
        }
    }
    stage("Run unit tests")
    {
        steps{
            dir("express-repo")
            {
                sh 'npm test'
            }
        }
    }
    stage("OWASP Dependency Check")
    {
        steps{
            dependencyCheck odcInstallation: 'OWASP Dependency Check', additionalArguments: '--format XML --scan "express-repo/examples/hello-world"'
        }
    }
  }
}