pipeline{
agent any

environment{
    MONGO_URI = credentials('mongo-uri')
    MONGO_USERNAME = credentials('mongo-db-username')
    MONGO_PASSWORD = credentials('mongo-db-password')
}
tools {
    nodejs  "nodejs-22-6-0"
}

 stages{
    stage('Install Dependencies'){
        steps{
             sh 'npm install --no-audit'
        }
    }
    stage('NPM Dependency Audit'){
        steps{
            sh 'npm install --audit-level=critical || true'
        }
    }
    stage('Unit Tests'){
        steps{
            sh 'npm test'
        }
    }
    stage('Code Coverage')
    {
        steps{
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE',message:"Will be fixed in subsequent builds")
            {
                sh 'npm run coverage'
            }
        }
    }
    stage('Build Docker Image'){
        steps{
            script{
                sh 'docker build -t kodekloud-hub:5000/solar-system:${GIT_COMMIT} .'
            }
        }
    }
    stage('Trivy Scan')
    {
        steps{
            sh '''
               trivy image kodekloud-hub:5000/solar-system:${GIT_COMMIT} \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      --format json -o trivy-image-CRITICAL-results.json
            '''
        }
    }
    stage('Localstack Aws S3')
    {
        when {
            expression {return env.GIT_BRANCH == ~ /feature\/.*/}
        }

        steps{
            withAws(credentials:'localstack-aws-credentials',endpointUrl: 'http://localhost:4566', region:'us-east-1'){
                sh '''
                ls -ltr 
                mkdir reports-$BUILD_ID
                cp -rf coverage/ reports-$BUILD_ID
                cp test-results.xml trivy*.* reports-$BUILD_ID/
                ls -ltr reports-$BUILD_ID/
                '''
            }
            s3Upload(file:"reports-$BUILD_ID",
            bucket:'solar-system-jenkins-reports-bucket',
            path:"reports-$BUILD_ID",
            pathStyleAccessEnabled: true
            )
        }
    }

    stage("Deploy to VM")
    {
        when {
            expression {return env.GIT_BRANCH == ~ /feature\/.*/}
        }
        steps{
            script{
                sshagent(['solar-system-jenkins-ssh-credentials']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no -i root@node01 "
                    if sudo docker ps -a | grep -q 'solar-system': then
                        echo 'Stopping existing solar-system container...'
                        sudo docker stop 'solar-system' && sudo docker rm 'solar-system'
                        echo 'container stopped and removed successfully.'
                    fi
                    sudo docker run --name solar-system 
                    -e MONGO_URI=$MONGO_URI \
                    -e MONGO_USERNAME=$MONGO_USERNAME \
                    -e MONGO_PASSWORD=$MONGO_PASSWORD \
                    -p 3000:3000 -d kodekloud-hub:5000/solar-system:$GIT_COMMIT

                    '''
                }
            }
        }
    }

 }
 post {
      always {

        junit allowEmptyResults: true, stdioRetention: '', testResults: 'coverage/lcov-report/*.xml'

        publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: true,
        reportDir: 'coverage/lcov-report', reportFiles: 'index.html', reportName: 'Code Coverage HTML report', reportTitles: '', useWrapperFileDirectly: true])

        sh 'trivy convert --format template --template /usr/local/share/trivy/templates/html.tpl --output trivy-image-CRITICAL-results.html trivy-image-CRITICAL-results.json'
        publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: true, reportDir: "./", reportFiles: "trivy-image-CRITICAL-results.html", reportName: "Trivy Image Critical Vul Report", reportTitles: "", useWrapperFileDirectly: true])
      }
    }


}